[package]
name = "record_linker"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5.1"
clap = { version = "4.5.4", features = ["derive"] }
glob = "0.3.1"
rand = "0.8.5"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
